one:
  num_sim: 100
  grid_size: 10
  num_sensors: 5
  num_actions: 4
  n_cell: 2
  mean_death: 100
  std_death: 5
  mean_sex: 0.5
  std_sex: 0.1
  mean_strength: 100
  std_strength: 20
  mean_velocity: 1
  std_velocity: 0.3